/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "cashier.payment": [
        {
            "name": "id",
            "required": true
        }
    ],
    "cashier.webhook": [],
    "login": [],
    "logout": [],
    "password.request": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.email": [],
    "password.update": [],
    "register": [],
    "user-profile-information.update": [],
    "user-password.update": [],
    "password.confirmation": [],
    "password.confirm": [],
    "two-factor.login": [],
    "two-factor.enable": [],
    "two-factor.confirm": [],
    "two-factor.disable": [],
    "two-factor.qr-code": [],
    "two-factor.secret-key": [],
    "two-factor.recovery-codes": [],
    "sanctum.csrf-cookie": [],
    "stancl.tenancy.asset": [
        {
            "name": "path",
            "required": false
        }
    ],
    "api.biometric.webhook": [],
    "api.biometric.heartbeat": [],
    "api.biometric-devices.commands.queue": [
        {
            "name": "deviceId",
            "required": true
        }
    ],
    "api.biometric-devices.commands.index": [
        {
            "name": "deviceId",
            "required": true
        }
    ],
    "api.biometric-devices.logs.index": [
        {
            "name": "deviceId",
            "required": true
        }
    ],
    "api.biometric-devices.logs.all": [],
    "api.version.current": [],
    "api.version.check": [],
    "api.system-monitoring.metrics": [],
    "api.system-monitoring.overview": [],
    "api.locale.index": [],
    "api.locale.update": [],
    "api.locale.translations": [
        {
            "name": "namespace",
            "required": false
        }
    ],
    "api.roles.index": [],
    "api.roles.store": [],
    "api.roles.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "api.roles.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "api.roles.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "api.roles.permissions.batch": [
        {
            "name": "id",
            "required": true
        }
    ],
    "api.roles.permissions.sync": [
        {
            "name": "id",
            "required": true
        }
    ],
    "api.permissions.index": [],
    "api.permissions.store": [],
    "api.permissions.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "api.permissions.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "api.permissions.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "api.permissions.grouped": [],
    "api.users.roles.index": [
        {
            "name": "id",
            "required": true
        }
    ],
    "api.users.roles.sync": [
        {
            "name": "id",
            "required": true
        }
    ],
    "api.users.permissions.index": [
        {
            "name": "id",
            "required": true
        }
    ],
    "api.users.permissions.sync": [
        {
            "name": "id",
            "required": true
        }
    ],
    "api.users.permissions.give": [
        {
            "name": "id",
            "required": true
        }
    ],
    "api.users.permissions.revoke": [
        {
            "name": "id",
            "required": true
        }
    ],
    "api.v1.auth.login": [],
    "api.v1.auth.refresh": [],
    "api.v1.client-errors.store": [],
    "api.v1.auth.me": [],
    "api.v1.heartbeat": [],
    "api.v1.config.show": [],
    "api.v1.auth.logout": [],
    "api.v1.profile.show": [],
    "api.v1.profile.update": [],
    "api.v1.profile.image.upload": [],
    "api.v1.profile.image.remove": [],
    "api.v1.attendance.today": [],
    "api.v1.attendance.present-users": [],
    "api.v1.attendance.absent-users": [],
    "api.v1.attendance.team-day": [],
    "api.v1.attendance.mark-present": [],
    "api.v1.attendance.locations-today": [],
    "api.v1.attendance.check-user-locations-updates": [
        {
            "name": "date",
            "required": true
        }
    ],
    "api.v1.attendance.check-timesheet-updates": [
        {
            "name": "date",
            "required": true
        },
        {
            "name": "month",
            "required": false
        }
    ],
    "api.v1.attendance.daily-timesheet": [],
    "api.v1.attendance.team-locations": [],
    "api.v1.attendance.monthly-summary": [],
    "api.v1.attendance.history": [],
    "api.v1.attendance.punch": [],
    "api.v1.attendance.my-roster": [],
    "api.v1.attendance.roster": [],
    "api.v1.attendance.shifts": [],
    "api.v1.attendance.regularizations.store": [],
    "api.v1.attendance.regularizations.mine": [],
    "api.v1.attendance.regularizations.pending": [],
    "api.v1.attendance.regularizations.decided": [],
    "api.v1.attendance.regularizations.approve": [
        {
            "name": "id",
            "required": true
        }
    ],
    "api.v1.attendance.regularizations.reject": [
        {
            "name": "id",
            "required": true
        }
    ],
    "api.v1.attendance.overtime.store": [],
    "api.v1.attendance.overtime.mine": [],
    "api.v1.attendance.overtime.pending": [],
    "api.v1.attendance.overtime.decided": [],
    "api.v1.attendance.overtime.approve": [
        {
            "name": "id",
            "required": true
        }
    ],
    "api.v1.attendance.overtime.reject": [
        {
            "name": "id",
            "required": true
        }
    ],
    "api.v1.attendance.swaps.pending": [],
    "api.v1.attendance.swaps.team-decided": [],
    "api.v1.attendance.swaps.approve": [
        {
            "name": "id",
            "required": true
        }
    ],
    "api.v1.attendance.swaps.reject": [
        {
            "name": "id",
            "required": true
        }
    ],
    "api.v1.attendance.compoff.mine": [],
    "api.v1.attendance.swaps.store": [],
    "api.v1.attendance.swaps.mine": [],
    "api.v1.attendance.swaps.awaiting-me": [],
    "api.v1.attendance.swaps.respond": [
        {
            "name": "id",
            "required": true
        }
    ],
    "api.v1.attendance.swaps.eligible": [],
    "api.v1.attendance.swaps.counterparty-roster": [],
    "api.v1.attendance.swaps.pickup": [],
    "api.v1.leave-types.index": [],
    "api.v1.leaves.index": [],
    "api.v1.leaves.summary": [],
    "api.v1.leaves.analytics": [],
    "api.v1.leaves.calendar": [],
    "api.v1.leaves.pending-approvals": [],
    "api.v1.leaves.decided-approvals": [],
    "api.v1.leaves.show": [
        {
            "name": "leaveId",
            "required": true
        }
    ],
    "api.v1.manager.dashboard.summary": [],
    "api.v1.manager.team-members": [],
    "api.v1.leaves.store": [],
    "api.v1.leaves.update": [
        {
            "name": "leaveId",
            "required": true
        }
    ],
    "api.v1.leaves.approve": [
        {
            "name": "leaveId",
            "required": true
        }
    ],
    "api.v1.leaves.reject": [
        {
            "name": "leaveId",
            "required": true
        }
    ],
    "api.v1.leaves.bulk-approve": [],
    "api.v1.leaves.bulk-reject": [],
    "api.v1.leaves.destroy": [
        {
            "name": "leaveId",
            "required": true
        }
    ],
    "api.v1.sync.bootstrap": [],
    "api.v1.sync.pull": [],
    "api.v1.sync.push": [],
    "api.v1.daily-works.index": [],
    "api.v1.daily-works.selectable-dates": [],
    "api.v1.daily-works.objections.metadata": [],
    "api.v1.daily-works.objections.my": [],
    "api.v1.daily-works.objections.queue": [],
    "api.v1.daily-works.show": [
        {
            "name": "dailyWorkId",
            "required": true
        }
    ],
    "api.v1.daily-works.status.update": [
        {
            "name": "dailyWorkId",
            "required": true
        }
    ],
    "api.v1.daily-works.incharge.update": [
        {
            "name": "dailyWorkId",
            "required": true
        }
    ],
    "api.v1.daily-works.assigned.update": [
        {
            "name": "dailyWorkId",
            "required": true
        }
    ],
    "api.v1.daily-works.objections.index": [
        {
            "name": "dailyWorkId",
            "required": true
        }
    ],
    "api.v1.daily-works.objections.store": [
        {
            "name": "dailyWorkId",
            "required": true
        }
    ],
    "api.v1.daily-works.objections.submit": [
        {
            "name": "dailyWorkId",
            "required": true
        },
        {
            "name": "objectionId",
            "required": true
        }
    ],
    "api.v1.daily-works.objections.review": [
        {
            "name": "dailyWorkId",
            "required": true
        },
        {
            "name": "objectionId",
            "required": true
        }
    ],
    "api.v1.daily-works.objections.resolve": [
        {
            "name": "dailyWorkId",
            "required": true
        },
        {
            "name": "objectionId",
            "required": true
        }
    ],
    "api.v1.daily-works.objections.reject": [
        {
            "name": "dailyWorkId",
            "required": true
        },
        {
            "name": "objectionId",
            "required": true
        }
    ],
    "api.v1.daily-works.objections.files.index": [
        {
            "name": "dailyWorkId",
            "required": true
        },
        {
            "name": "objectionId",
            "required": true
        }
    ],
    "api.v1.daily-works.objections.files.upload": [
        {
            "name": "dailyWorkId",
            "required": true
        },
        {
            "name": "objectionId",
            "required": true
        }
    ],
    "api.v1.daily-works.objections.files.delete": [
        {
            "name": "dailyWorkId",
            "required": true
        },
        {
            "name": "objectionId",
            "required": true
        },
        {
            "name": "mediaId",
            "required": true
        }
    ],
    "api.v1.daily-works.objections.files.download": [
        {
            "name": "dailyWorkId",
            "required": true
        },
        {
            "name": "objectionId",
            "required": true
        },
        {
            "name": "mediaId",
            "required": true
        }
    ],
    "api.v1.notifications.token.store": [],
    "api.v1.om.dashboard": [],
    "api.v1.om.traffic": [],
    "api.v1.om.toll": [],
    "api.v1.om.incidents": [],
    "api.v1.om.incidents.store": [],
    "api.v1.om.work-orders": [],
    "api.v1.om.work-orders.store": [],
    "api.v1.om.defects": [],
    "api.v1.om.defects.store": [],
    "api.v1.om.assets": [],
    "api.v1.om.equipment": [],
    "api.v1.om.shift-logs": [],
    "api.v1.om.vms.update": [],
    "api.v1.om.field.overview": [],
    "api.v1.om.field.defect.log": [],
    "api.v1.om.field.incident.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "api.v1.om.field.work-order.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "api.v1.account.change-password": [],
    "api.v1.account.devices.index": [],
    "api.v1.account.devices.revoke": [
        {
            "name": "device",
            "required": true
        }
    ],
    "api.v1.account.sign-out-all": [],
    "install-app": [],
    "apk.download": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "locale.update": [],
    "firebase.token": [],
    "dashboard": [],
    "dashboard.command": [],
    "stats": [],
    "employee-dashboard": [],
    "search": [],
    "quality.ncr.index": [],
    "quality.ncr.store": [],
    "quality.ncr.update": [
        {
            "name": "ncr",
            "required": true,
            "binding": "id"
        }
    ],
    "quality.ncr.transition": [
        {
            "name": "ncr",
            "required": true,
            "binding": "id"
        }
    ],
    "quality.ncr.destroy": [
        {
            "name": "ncr",
            "required": true,
            "binding": "id"
        }
    ],
    "security.dashboard": [],
    "updates": [],
    "leaves-employee": [],
    "leave-add": [],
    "leave-update": [],
    "leave-delete": [],
    "leaves.cancel": [
        {
            "name": "id",
            "required": true
        }
    ],
    "leaves.attachments.download": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "mediaId",
            "required": true
        }
    ],
    "leaves.attachments.delete": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "mediaId",
            "required": true
        }
    ],
    "leaves.paginate": [],
    "leaves.stats": [],
    "leave-balances": [],
    "leave-ledger": [],
    "attendance-employee": [],
    "attendance.current-user-punch": [],
    "getCurrentUserAttendanceForDate": [],
    "attendance.myRoster": [],
    "attendance.swaps.store": [],
    "attendance.swaps.awaitingMe": [],
    "attendance.swaps.mine": [],
    "attendance.swaps.respond": [
        {
            "name": "id",
            "required": true
        }
    ],
    "attendance.swaps.eligible": [],
    "attendance.swaps.counterpartyRoster": [],
    "attendance.swaps.pickup": [],
    "attendance.regularizations.store": [],
    "attendance.regularizations.mine": [],
    "attendance.overtime.store": [],
    "attendance.overtime.mine": [],
    "attendance.compoff.mine": [],
    "attendance.punch": [],
    "attendance.exportExcel": [],
    "attendance.exportAdminExcel": [],
    "attendance.exportAdminPdf": [],
    "attendance.exportPdf": [],
    "getPresentUsersForDate": [],
    "getAbsentUsersForDate": [],
    "getClientIp": [],
    "attendance.exportStatus": [
        {
            "name": "filename",
            "required": true
        }
    ],
    "daily-works-unified": [],
    "dailyWorks.paginate": [],
    "dailyWorks.all": [],
    "daily-works-summary.filter": [],
    "dailyWorks.statistics": [],
    "dailyWorks.updateStatus": [],
    "dailyWorks.updateCompletionTime": [],
    "dailyWorks.updateSubmissionTime": [],
    "dailyWorks.bulkSubmit": [],
    "dailyWorks.bulkImportSubmit": [],
    "dailyWorks.bulkImportTemplate": [],
    "dailyWorks.bulkResponseStatusUpdate": [],
    "dailyWorks.bulkImportResponseStatus": [],
    "dailyWorks.downloadResponseStatusTemplate": [],
    "dailyWorks.bulkUpdateIncharge": [],
    "dailyWorks.bulkUpdateStatus": [],
    "dailyWorks.bulkUpdateCompletionDate": [],
    "dailyWorks.bulkDelete": [],
    "dailyWorks.exportObjectedRfis": [],
    "dailyWorks.updateAssigned": [],
    "dailyWorks.uploadRFI": [],
    "dailyWorks.updateInspectionDetails": [],
    "dailyWorks.rfiFiles.upload": [
        {
            "name": "dailyWork",
            "required": true,
            "binding": "id"
        }
    ],
    "dailyWorks.rfiFiles.index": [
        {
            "name": "dailyWork",
            "required": true,
            "binding": "id"
        }
    ],
    "dailyWorks.rfiFiles.delete": [
        {
            "name": "dailyWork",
            "required": true,
            "binding": "id"
        },
        {
            "name": "mediaId",
            "required": true
        }
    ],
    "dailyWorks.rfiFiles.download": [
        {
            "name": "dailyWork",
            "required": true,
            "binding": "id"
        },
        {
            "name": "mediaId",
            "required": true
        }
    ],
    "dailyWorks.objections.index": [
        {
            "name": "dailyWork",
            "required": true,
            "binding": "id"
        }
    ],
    "dailyWorks.objections.available": [
        {
            "name": "dailyWork",
            "required": true,
            "binding": "id"
        }
    ],
    "dailyWorks.objections.show": [
        {
            "name": "dailyWork",
            "required": true,
            "binding": "id"
        },
        {
            "name": "objection",
            "required": true,
            "binding": "id"
        }
    ],
    "dailyWorks.objections.metadata": [],
    "dailyWorks.objections.files": [
        {
            "name": "dailyWork",
            "required": true,
            "binding": "id"
        },
        {
            "name": "objection",
            "required": true,
            "binding": "id"
        }
    ],
    "dailyWorks.objections.files.download": [
        {
            "name": "dailyWork",
            "required": true,
            "binding": "id"
        },
        {
            "name": "objection",
            "required": true,
            "binding": "id"
        },
        {
            "name": "mediaId",
            "required": true
        }
    ],
    "dailyWorks.objections.store": [
        {
            "name": "dailyWork",
            "required": true,
            "binding": "id"
        }
    ],
    "dailyWorks.objections.attach": [
        {
            "name": "dailyWork",
            "required": true,
            "binding": "id"
        }
    ],
    "dailyWorks.objections.detach": [
        {
            "name": "dailyWork",
            "required": true,
            "binding": "id"
        }
    ],
    "dailyWorks.objections.update": [
        {
            "name": "dailyWork",
            "required": true,
            "binding": "id"
        },
        {
            "name": "objection",
            "required": true,
            "binding": "id"
        }
    ],
    "dailyWorks.objections.destroy": [
        {
            "name": "dailyWork",
            "required": true,
            "binding": "id"
        },
        {
            "name": "objection",
            "required": true,
            "binding": "id"
        }
    ],
    "dailyWorks.objections.submit": [
        {
            "name": "dailyWork",
            "required": true,
            "binding": "id"
        },
        {
            "name": "objection",
            "required": true,
            "binding": "id"
        }
    ],
    "dailyWorks.objections.files.upload": [
        {
            "name": "dailyWork",
            "required": true,
            "binding": "id"
        },
        {
            "name": "objection",
            "required": true,
            "binding": "id"
        }
    ],
    "dailyWorks.objections.files.delete": [
        {
            "name": "dailyWork",
            "required": true,
            "binding": "id"
        },
        {
            "name": "objection",
            "required": true,
            "binding": "id"
        },
        {
            "name": "mediaId",
            "required": true
        }
    ],
    "dailyWorks.objections.review": [
        {
            "name": "dailyWork",
            "required": true,
            "binding": "id"
        },
        {
            "name": "objection",
            "required": true,
            "binding": "id"
        }
    ],
    "dailyWorks.objections.resolve": [
        {
            "name": "dailyWork",
            "required": true,
            "binding": "id"
        },
        {
            "name": "objection",
            "required": true,
            "binding": "id"
        }
    ],
    "dailyWorks.objections.reject": [
        {
            "name": "dailyWork",
            "required": true,
            "binding": "id"
        },
        {
            "name": "objection",
            "required": true,
            "binding": "id"
        }
    ],
    "objections.index": [],
    "objections.store": [],
    "objections.update": [
        {
            "name": "objection",
            "required": true,
            "binding": "id"
        }
    ],
    "objections.destroy": [
        {
            "name": "objection",
            "required": true,
            "binding": "id"
        }
    ],
    "objections.attachRfis": [
        {
            "name": "objection",
            "required": true,
            "binding": "id"
        }
    ],
    "objections.detachRfis": [
        {
            "name": "objection",
            "required": true,
            "binding": "id"
        }
    ],
    "objections.suggestRfis": [],
    "objections.exportSuggestedRfis": [],
    "objections.submit": [
        {
            "name": "objection",
            "required": true,
            "binding": "id"
        }
    ],
    "objections.review": [
        {
            "name": "objection",
            "required": true,
            "binding": "id"
        }
    ],
    "objections.resolve": [
        {
            "name": "objection",
            "required": true,
            "binding": "id"
        }
    ],
    "objections.reject": [
        {
            "name": "objection",
            "required": true,
            "binding": "id"
        }
    ],
    "objections.export": [],
    "dailyWorks.add": [],
    "dailyWorks.update": [],
    "daily-works-summary.refresh": [],
    "dailyWorks.updateIncharge": [],
    "dailyWorks.assign": [],
    "dailyWorks.delete": [],
    "dailyWorks.export": [],
    "daily-works-summary.export": [],
    "daily-works-summary.export-excel": [],
    "daily-works-summary.export-pdf": [],
    "daily-works-summary.analytics": [],
    "daily-works-summary.statistics": [],
    "holidays": [],
    "api.holidays": [],
    "holidays.stats": [],
    "api.holidays.show": [
        {
            "name": "holiday",
            "required": true,
            "binding": "id"
        }
    ],
    "holidays-legacy": [],
    "holidays-add": [],
    "holidays-delete": [],
    "profile": [
        {
            "name": "user",
            "required": true,
            "binding": "employee_id"
        }
    ],
    "profile.stats": [
        {
            "name": "user",
            "required": true,
            "binding": "employee_id"
        }
    ],
    "profile.export": [
        {
            "name": "user",
            "required": true,
            "binding": "employee_id"
        }
    ],
    "profile.trackView": [
        {
            "name": "user",
            "required": true,
            "binding": "employee_id"
        }
    ],
    "profile.update": [],
    "profile.delete": [],
    "profile.image.upload": [],
    "profile.image.remove": [],
    "education.update": [],
    "education.delete": [],
    "experience.update": [],
    "experience.delete": [],
    "leave-summary": [],
    "letters": [],
    "letters.paginate": [],
    "letters.update": [],
    "leaves.index": [],
    "leave.summary.exportExcel": [],
    "leave.summary.exportPdf": [],
    "leaves.analytics": [],
    "leaves.pending-approvals": [],
    "leaves.bulk-approve": [],
    "leaves.bulk-reject": [],
    "leaves.bulk-status-update": [],
    "leaves.approve": [
        {
            "name": "id",
            "required": true
        }
    ],
    "leaves.reject": [
        {
            "name": "id",
            "required": true
        }
    ],
    "leave-update-status": [],
    "leaves.bulk.validate": [],
    "leaves.bulk.store": [],
    "leaves.bulk.leave-types": [],
    "leaves.bulk.calendar-data": [],
    "leaves.bulk.delete": [],
    "leave-settings": [],
    "add-leave-type": [],
    "update-leave-type": [
        {
            "name": "id",
            "required": true
        }
    ],
    "delete-leave-type": [
        {
            "name": "id",
            "required": true
        }
    ],
    "employees": [],
    "employees.paginate": [],
    "employees.stats": [],
    "employees.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "organization.index": [],
    "departments": [],
    "api.departments": [],
    "departments.stats": [],
    "departments.store": [],
    "departments.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "departments.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "departments.delete": [
        {
            "name": "id",
            "required": true
        }
    ],
    "users.update-department": [
        {
            "name": "id",
            "required": true
        }
    ],
    "users.updateDesignation": [
        {
            "name": "id",
            "required": true
        }
    ],
    "users.updateWorkLocation": [
        {
            "name": "id",
            "required": true
        }
    ],
    "jurisdiction": [],
    "dailyWorks.previewImport": [],
    "dailyWorks.import": [],
    "dailyWorks.downloadTemplate": [],
    "holiday-add": [],
    "api.holidays.store": [],
    "holiday-update": [
        {
            "name": "holiday",
            "required": true,
            "binding": "id"
        }
    ],
    "api.holidays.update": [
        {
            "name": "holiday",
            "required": true,
            "binding": "id"
        }
    ],
    "holidays-restore": [],
    "holidays-copy-year": [],
    "holiday-delete": [],
    "api.holidays.destroy": [
        {
            "name": "holiday",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.unified": [],
    "users": [],
    "users.paginate": [],
    "users.stats": [],
    "profiles.search": [],
    "users.store": [],
    "addUser": [],
    "users.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "users.updateRole": [
        {
            "name": "id",
            "required": true
        }
    ],
    "users.changePassword": [
        {
            "name": "id",
            "required": true
        }
    ],
    "users.restore": [
        {
            "name": "id",
            "required": true
        }
    ],
    "users.updateAttendanceType": [
        {
            "name": "userId",
            "required": true
        }
    ],
    "users.updateBiometricDevice": [
        {
            "name": "id",
            "required": true
        }
    ],
    "users.updateReportTo": [
        {
            "name": "id",
            "required": true
        }
    ],
    "users.bulk.role": [],
    "users.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "users.bulk.delete": [],
    "user.delete": [
        {
            "name": "id",
            "required": true
        }
    ],
    "user.devices": [],
    "user.devices.deactivate": [
        {
            "name": "deviceId",
            "required": true
        }
    ],
    "admin.users.devices": [
        {
            "name": "userId",
            "required": true
        }
    ],
    "admin.device-sessions.index": [],
    "admin.users.devices.reset": [
        {
            "name": "userId",
            "required": true
        }
    ],
    "admin.users.devices.toggle": [
        {
            "name": "userId",
            "required": true
        }
    ],
    "admin.users.devices.deactivate": [
        {
            "name": "userId",
            "required": true
        },
        {
            "name": "deviceId",
            "required": true
        }
    ],
    "admin.device-sessions.revoke": [
        {
            "name": "device",
            "required": true
        }
    ],
    "admin.feature-flags.index": [],
    "admin.feature-flags.store": [],
    "admin.feature-flags.update": [
        {
            "name": "flag",
            "required": true
        }
    ],
    "admin.feature-flags.toggle": [
        {
            "name": "flag",
            "required": true
        }
    ],
    "admin.feature-flags.destroy": [
        {
            "name": "flag",
            "required": true
        }
    ],
    "admin.client-errors.index": [],
    "admin.client-errors.show": [
        {
            "name": "error",
            "required": true
        }
    ],
    "admin.client-errors.resolve": [
        {
            "name": "error",
            "required": true
        }
    ],
    "update-company-settings": [],
    "admin.settings.company": [],
    "roles-settings": [],
    "attendances": [],
    "timesheet": [],
    "attendance.unified": [],
    "attendancesAdmin.paginate": [],
    "admin.daily-timesheet": [],
    "attendance.log": [],
    "getUserLocationsForDate": [],
    "admin.getPresentUsersForDate": [],
    "admin.getAbsentUsersForDate": [],
    "attendance.dayPartition": [],
    "attendance.monthlyStats": [],
    "attendance.dailyOverview": [],
    "attendance.audit.history": [
        {
            "name": "id",
            "required": true
        }
    ],
    "check-user-locations-updates": [
        {
            "name": "date",
            "required": true
        }
    ],
    "check-timesheet-updates": [
        {
            "name": "date",
            "required": true
        },
        {
            "name": "month",
            "required": false
        }
    ],
    "attendance.dailyTimesheet.export": [],
    "attendance.monthlyCalendar.export": [],
    "attendance.log.export": [],
    "attendance.mark-as-present": [],
    "attendance.bulk-mark-as-present": [],
    "attendance.regularizations.pending": [],
    "attendance.regularizations.approve": [
        {
            "name": "id",
            "required": true
        }
    ],
    "attendance.regularizations.reject": [
        {
            "name": "id",
            "required": true
        }
    ],
    "attendance.punch-exceptions.pending": [],
    "attendance.punch-exceptions.approve": [
        {
            "name": "id",
            "required": true
        }
    ],
    "attendance.punch-exceptions.reject": [
        {
            "name": "id",
            "required": true
        }
    ],
    "attendance.overtime.pending": [],
    "attendance.overtime.approve": [
        {
            "name": "id",
            "required": true
        }
    ],
    "attendance.overtime.reject": [
        {
            "name": "id",
            "required": true
        }
    ],
    "attendance.correct.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "attendance.correct.add": [],
    "attendance.correct.delete": [
        {
            "name": "id",
            "required": true
        }
    ],
    "attendance.correct.status": [
        {
            "name": "id",
            "required": true
        }
    ],
    "attendance.myMonthlyStats": [],
    "attendance.myScheduleToday": [],
    "attendance-settings.update": [],
    "attendance-types.store": [],
    "attendance-types.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "attendance-types.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "attendance-types.addItem": [
        {
            "name": "id",
            "required": true
        }
    ],
    "attendance-types.removeItem": [
        {
            "name": "id",
            "required": true
        }
    ],
    "attendance-types.generateQr": [
        {
            "name": "id",
            "required": true
        }
    ],
    "biometric-devices.index": [],
    "biometric-devices.store": [],
    "biometric-devices.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "biometric-devices.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "biometric-devices.sync-pool": [],
    "biometric-devices.regenerate-token": [
        {
            "name": "id",
            "required": true
        }
    ],
    "biometric-devices.regenerate-adms-token": [
        {
            "name": "id",
            "required": true
        }
    ],
    "biometric-devices.active": [],
    "biometric-devices.ping": [
        {
            "name": "id",
            "required": true
        }
    ],
    "biometric-devices.logs": [],
    "biometric-devices.health": [],
    "biometric-devices.operlogs": [],
    "biometric-devices.attlogs": [],
    "biometric-devices.attlogs.link-user": [],
    "biometric-devices.templates": [],
    "biometric-devices.restore-templates": [
        {
            "name": "id",
            "required": true
        }
    ],
    "biometric-devices.delete-template": [
        {
            "name": "id",
            "required": true
        }
    ],
    "biometric-devices.settings-catalogue": [],
    "biometric-devices.capabilities": [
        {
            "name": "id",
            "required": true
        }
    ],
    "biometric-devices.probe": [
        {
            "name": "id",
            "required": true
        }
    ],
    "biometric-devices.settings.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "biometric-devices.reconciliation": [
        {
            "name": "id",
            "required": true
        }
    ],
    "biometric-devices.bulk.ping": [],
    "biometric-devices.bulk.delete": [],
    "biometric-devices.download-logs": [
        {
            "name": "id",
            "required": true
        }
    ],
    "biometric-devices.bulk.download-logs": [],
    "biometric-devices.download-history": [],
    "biometric-devices.download-sessions.logs": [
        {
            "name": "id",
            "required": true
        }
    ],
    "biometric-devices.download-sessions.import": [
        {
            "name": "id",
            "required": true
        }
    ],
    "request-logs.index": [],
    "request-logs.list": [],
    "request-logs.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "request-logs.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "request-logs.bulk-delete": [],
    "request-logs.clear-all": [],
    "request-logs.export": [],
    "attendance.shifts.index": [],
    "attendance.patterns.index": [],
    "attendance.assignments.index": [],
    "attendance.roster.index": [],
    "attendance.shifts.store": [],
    "attendance.shifts.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "attendance.shifts.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "attendance.patterns.store": [],
    "attendance.patterns.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "attendance.patterns.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "attendance.assignments.store": [],
    "attendance.assignments.storeBulk": [],
    "attendance.assignments.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "attendance.assignments.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "attendance.roster.generate": [],
    "attendance.roster.cell": [],
    "attendance.coverage.index": [],
    "attendance.workLocations.index": [],
    "attendance.coverageRequirements.index": [],
    "attendance.coverageRequirements.store": [],
    "attendance.coverageRequirements.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "attendance.coverageRequirements.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "attendance.swaps.index": [],
    "attendance.swaps.approve": [
        {
            "name": "id",
            "required": true
        }
    ],
    "attendance.swaps.reject": [
        {
            "name": "id",
            "required": true
        }
    ],
    "attendance.policies.index": [],
    "attendance.policies.simulate": [],
    "attendance.policies.store": [],
    "attendance.policies.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "attendance.policies.activate": [
        {
            "name": "id",
            "required": true
        }
    ],
    "allTasks": [],
    "addTask": [],
    "showWorkLocations": [],
    "allWorkLocations": [],
    "workLocations.show": [
        {
            "name": "workLocation",
            "required": true,
            "binding": "id"
        }
    ],
    "addWorkLocation": [],
    "deleteWorkLocation": [],
    "updateWorkLocation": [],
    "allJurisdictions": [],
    "addJurisdiction": [],
    "deleteJurisdiction": [],
    "updateJurisdiction": [],
    "roles": [],
    "admin.roles-management": [],
    "admin.roles.audit": [],
    "admin.roles.export": [],
    "admin.roles.metrics": [],
    "admin.roles.snapshot": [],
    "admin.roles.store": [],
    "admin.roles.clone": [],
    "admin.roles.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.roles.update-permission": [],
    "admin.roles.toggle-permission": [],
    "admin.roles.update-module": [],
    "admin.roles.bulk-operation": [],
    "admin.roles.batch-permissions": [
        {
            "name": "role",
            "required": true
        }
    ],
    "admin.roles.delete": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.roles.initialize-enterprise": [],
    "admin.roles.test": [],
    "modules.index": [],
    "modules.api.index": [],
    "modules.statistics": [],
    "modules.check-access": [],
    "modules.store": [],
    "modules.sub-modules.store": [
        {
            "name": "module",
            "required": true
        }
    ],
    "modules.components.store": [
        {
            "name": "subModule",
            "required": true
        }
    ],
    "modules.update": [
        {
            "name": "module",
            "required": true
        }
    ],
    "modules.sub-modules.update": [
        {
            "name": "subModule",
            "required": true
        }
    ],
    "modules.components.update": [
        {
            "name": "component",
            "required": true
        }
    ],
    "modules.sync-permissions": [
        {
            "name": "module",
            "required": true
        }
    ],
    "modules.sub-modules.sync-permissions": [
        {
            "name": "subModule",
            "required": true
        }
    ],
    "modules.components.sync-permissions": [
        {
            "name": "component",
            "required": true
        }
    ],
    "modules.destroy": [
        {
            "name": "module",
            "required": true
        }
    ],
    "modules.sub-modules.destroy": [
        {
            "name": "subModule",
            "required": true
        }
    ],
    "modules.components.destroy": [
        {
            "name": "component",
            "required": true
        }
    ],
    "admin.system-monitoring": [],
    "admin.errors.resolve": [
        {
            "name": "errorId",
            "required": true
        }
    ],
    "admin.system-report": [],
    "admin.optimization-report": [],
    "designations.index": [],
    "designations.json": [],
    "designations.stats": [],
    "designations.list": [],
    "designations.store": [],
    "designations.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "designations.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "designations.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "api.designations.list": [],
    "departments.list": [],
    "users.managers.list": [],
    "updateFcmToken": [],
    "service-worker": [],
    "petty-cash.index": [],
    "petty-cash.loan": [],
    "petty-cash.loan.approve": [],
    "petty-cash.loan.reject": [],
    "petty-cash.loan.close": [],
    "petty-cash.expense": [],
    "petty-cash.reimbursement": [],
    "petty-cash.repayment": [],
    "petty-cash.transaction.update": [],
    "petty-cash.transaction.delete": [],
    "petty-cash.transactions": [],
    "petty-cash.analytics": [],
    "petty-cash.upload-bill": [],
    "petty-cash.delete-bill": [],
    "petty-cash.export": [],
    "petty-cash.export-pdf": [],
    "petty-cash.export.status": [
        {
            "name": "filename",
            "required": true
        }
    ],
    "petty-cash.history": [],
    "petty-cash.admin.overview": [],
    "petty-cash.categories": [],
    "petty-cash.audit-log": [],
    "om.dashboard": [],
    "om.defects": [],
    "om.defects.store": [],
    "om.defects.convert-wo": [
        {
            "name": "id",
            "required": true
        }
    ],
    "om.work-orders": [],
    "om.work-orders.store": [],
    "om.work-orders.approve": [
        {
            "name": "id",
            "required": true
        }
    ],
    "om.work-orders.start": [
        {
            "name": "id",
            "required": true
        }
    ],
    "om.work-orders.complete": [
        {
            "name": "id",
            "required": true
        }
    ],
    "om.work-orders.verify": [
        {
            "name": "id",
            "required": true
        }
    ],
    "om.incidents": [],
    "om.incidents.store": [],
    "om.incidents.status": [
        {
            "name": "id",
            "required": true
        }
    ],
    "om.incidents.damage-wo": [
        {
            "name": "id",
            "required": true
        }
    ],
    "om.assets": [],
    "om.assets.store": [],
    "om.traffic": [],
    "om.vms.update": [],
    "om.toll": [],
    "om.toll.audit.store": [],
    "om.equipment": [],
    "om.shift-logs": [],
    "om.shift-logs.store": [],
    "om.shift-logs.acknowledge": [
        {
            "name": "id",
            "required": true
        }
    ],
    "admin.settings.notifications": [],
    "settings.notifications": [],
    "notifications.index": [],
    "aeon.index": [],
    "aeon.message": [],
    "aeon.message.stream": [],
    "aeon.conversations.index": [],
    "aeon.conversations.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "aeon.conversations.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "aeon.messages.feedback": [
        {
            "name": "id",
            "required": true
        }
    ],
    "biometric.adms.handshake": [],
    "biometric.adms.push": [],
    "biometric.adms.getrequest": [],
    "biometric.adms.devicecmd": [],
    "biometric.adms.test": []
}
}
export {};
